name: Soins des mammifères

on:
  push:
    branches:
      - main
    paths:
      - "mammiferes/**"

jobs:
  soins:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher les informations
        run: |
          echo "Message du commit: ${{ github.event.head_commit.message }}"
          echo "Type d'événement: ${{ github.event_name }}"
          echo "Auteur: ${{ github.actor }}"
