name: "PizzaCI - Express"

on:
  workflow_dispatch:
    inputs:
      nom_client:
        description: "Nom du client"
        required: true
      pizzas:
        description: |
          Liste des pizzas au format JSON. Attention aux points importants:
          - Utilisez des guillemets doubles
          - Entourez la liste avec []
          Exemple: ["margherita","reine","calzone"]
        required: true

jobs:
  reception-commande:
    runs-on: ubuntu-latest
    outputs:
      commande_pizzas: ${{ steps.enregistrer-commande.outputs.pizzas_commandees }}
    steps:
      - name: Message d'accueil
        run: echo "Bienvenue chez PizzaCI - Express, ${{ github.event.inputs.nom_client }}!"

      - name: Confirmation de la commande
        run: |
        echo "Nous avons bien reçu votre commande de pizzas: ${{ github.event.inputs.pizzas }}"

      - name: Enregistrer la commande
        id: enregistrer-commande
        run: echo "pizzas_commandees=${{ github.event.inputs.pizzas }}" >> $GITHUB_OUTPUT

  cuisine:
    needs: reception-commande
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pizza: ${{ fromJSON(needs.reception-commande.outputs.commande_pizzas) }}
        taille: ["L", "XL"]
        include:
          - pizza: "dessert_gratuit"
            taille: "L"
    steps:
      - name: Préparer la pizza
        run: echo "Préparation en cours de la pizza ${{ matrix.pizza }} en taille ${{ matrix.taille }}"

  livraison:
    needs: cuisine
    runs-on: ubuntu-latest
    concurrency:
      group: livraison-${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - name: Préparation de la livraison
        run: echo "Préparation de la livraison pour ${{ github.event.inputs.nom_client }}"

      - name: Liste des pizzas à livrer
        run: |
          echo "Les pizzas à livrer sont : ${{ needs.reception-commande.outputs.commande_pizzas }}"

  reclamation:
    needs: livraison
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Création d'une issue en cas de réclamation
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create --title "Suivi de commande pour ${{ github.event.inputs.nom_client }}" --body "Commande de pizzas: ${{ needs.reception-commande.outputs.commande_pizzas }}\n\nMerci de nous faire savoir si tout s'est bien passé avec votre commande!"
